fix --author argument syntax
Without the angular brackets around the email address,
the `jj describe --author … …` command
would cause the following error message:

    error: invalid value 'Claire claire@local' for '--author <AUTHOR>': Invalid author string

    For more information, try '--help'.